name: Health Check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render server
        run: curl -f https://savhorserver.onrender.com/api/health
